version: '3.8'

services:
  postgres-course-service:
    image: postgres:16-alpine
    container_name: eduflow-postgres-course
    environment:
      POSTGRES_DB: ${COURSE_DB_NAME}
      POSTGRES_USER: ${COURSE_DB_USER}
      POSTGRES_PASSWORD: ${COURSE_DB_PASSWORD}
    ports:
      - "${COURSE_DB_PORT}:5432"
    volumes:
      - postgres_course_data:/var/lib/postgresql/data

  postgres-enrollment-service:
    image: postgres:16-alpine
    container_name: eduflow-postgres-enrollment
    environment:
      POSTGRES_DB: ${ENROLLMENT_DB_NAME}
      POSTGRES_USER: ${ENROLLMENT_DB_USER}
      POSTGRES_PASSWORD: ${ENROLLMENT_DB_PASSWORD}
    ports:
      - "${ENROLLMENT_DB_PORT}:5432"
    volumes:
      - postgres_enrollment_data:/var/lib/postgresql/data

  postgres-certificate-service:
    image: postgres:16-alpine
    container_name: eduflow-postgres-certificate
    environment:
      POSTGRES_DB: ${CERTIFICATE_DB_NAME}
      POSTGRES_USER: ${CERTIFICATE_DB_USER}
      POSTGRES_PASSWORD: ${CERTIFICATE_DB_PASSWORD}
    ports:
      - "${CERTIFICATE_DB_PORT}:5432"
    volumes:
      - postgres_certificate_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: eduflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  zipkin:
    image: openzipkin/zipkin
    container_name: eduflow-zipkin
    ports:
      - "9411:9411"

volumes:
  postgres_course_data:
  postgres_enrollment_data:
  postgres_certificate_data:
  rabbitmq_data: