server:
  port: 8084

spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://eduflow-config-server:8888"

eureka:
  client:
    service-url:
      defaultZone: http://eduflow-eureka-server:8761/eureka